FROM splunk/splunk:8.0-debian

ARG SPLUNK_PASSWORD

ENV INIT_DIR="/tmp/"
ENV SPLUNK_START_ARGS="--accept-license"

EXPOSE $WEB_PORT
EXPOSE $REST_API_PORT

RUN sudo mkdir -p $INIT_DIR
ADD ./init_files $INIT_DIR

RUN sudo apt update
RUN sudo apt install dos2unix -y
RUN sudo apt install tshark -y
RUN sudo apt install python3 python3-pip -y

ENV SPLUNK_PASSWORD $SPLUNK_PASSWORD
ENV SPLUNK_START_ARGS $SPLUNK_START_ARGS

RUN sudo dos2unix $INIT_DIR/traffic-analyzer-entrypoint.sh
RUN sudo chmod +x $INIT_DIR/traffic-analyzer-entrypoint.sh
ENTRYPOINT ["/tmp/traffic-analyzer-entrypoint.sh"]
